footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
footprint_padding: 0.01

#tf params (coord frame)
robot_base_frame: base_link
transform_tolerance: 0.5

#Rate params
update_frequency: 4.0
publish_frequency: 3.0

## Params that may be overwriten by layers.
# Map resolution metres/pixels
resolution: 0.05

# obstacle layer params
obstacle_range: 5.5
raytrace_range: 6.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}

inflation:
    inflation_radius: 1.0 #default 
    cost_scaling_factor: 10.0 #default 10.0
