global_costmap:
  global_frame: odom
  robot_base_frame: base_link
  width: 50.0
  height: 50.0
  origin_x: -25.000000
  origin_y: -25.000000
  #static_map: true
  #rolling_window: false #Because static param is set to true
  track_unknown_space: true

  plugins:
    - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
    - {name: inflation,                 type: "costmap_2d::InflationLayer"}