local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  width: 10.0
  height: 10.0
  static_map: false
  rolling_window: true


  plugins:
    - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
    - {name: inflation,                 type: "costmap_2d::InflationLayer"}