gazebo_ros_control:
  pid_gains:
    front_left_wheel:
      p: 1
      i: 0
      d: 1
    front_right_wheel:
      p: 1
      i: 0
      d: 1
    rear_left_wheel:
      p: 1
      i: 0
      d: 1
    rear_right_wheel:
      p: 1
      i: 0
      d: 1