scan_filter_chain:
- name: angle
  type: LaserScanAngularBoundsFilter
  params:
    lower_angle: -0.13084
    upper_angle: 1.70008
- name: ScanRange
  type: LaserScanBoxFilter
  params:
    box_frame: base_link
    min_x: -0.495
    max_x: 0.495
    min_y: -0.335
    max_y: 0.335
    min_z: -0.130
    max_z: 0.790