scan_filter_chain:
- name: AngleOne
  type: LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: 1.97
    upper_angle: 3.14
- name: AngleTwo
  type: LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: -3.14
    upper_angle: -1.97
- name: Box
  type: LaserScanBoxFilter
  params:
    box_frame: base_link
    min_x: -0.495
    max_x: 0.495
    min_y: -0.335
    max_y: 0.335
    min_z: -0.130
    max_z: 0.790