# For parameter descriptions, please refer to the template parameter files for each node.

ekf_se_odom:
  odom_frame: odom
  base_link_frame: base_link
  world_frame: odom
  map_frame: map

  two_d_mode: true

  frequency: 50

  odom0: husky_velocity_controller/odom
  odom0_config: [false, false, false,
                 false, false, false,
                 true, true, true,
                 false, false, true,
                 false, false, false]
  odom0_differential: false
  odom0_queue_size: 10

  imu0: imu/data
  imu0_config: [false, false, false,
                true, true, true,
                false, false, false,
                true, true, true,
                false, false, false]
  imu0_differential: true
  imu0_queue_size: 10
  imu0_remove_gravitational_acceleration: true

ekf_se_map:
  odom_frame: odom
  base_link_frame: base_link
  world_frame: map
  map_frame: map

  two_d_mode: true

  frequency: 50

  odom0: husky_velocity_controller/odom
  odom0_config: [false, false, false,
                 false, false, false,
                 true, true, true,
                 false, false, true,
                 false, false, false]
  odom0_differential: false
  odom0_queue_size: 10

  imu0: imu/data
  imu0_config: [false, false, false,
                true, true, true,
                false, false, false,
                true, true, true,
                false, false, false]
  imu0_differential: true
  imu0_queue_size: 10
  imu0_remove_gravitational_acceleration: true

  odom1: odometry/gps
  odom1_config: [true,  true,  false,
                 false, false, false,
                 false, false, false,
                 false, false, false,
                 false, false, false]
  odom1_queue_size: 10
  odom1_differential: false

navsat_transform:
  frequency: 50
  delay: 3.0
  magnetic_declination_radians: 0.00  #0.168285  # For lat/long 43.500718, -80.546638 on Jun 1 2017
  yaw_offset: 1.570796327  # IMU reads 0 facing magnetic north, not east
  zero_altitude: true
  broadcast_utm_transform: true
  publish_filtered_gps: true
  use_odometry_yaw: false
  wait_for_datum: false