collector:
  keyboard_option: 0
  collect_button_num: 1
  end_button_num1: 4
  end_button_num2: 5
  key_collect_button: 1
  key_end_button: 2
  coordinates_file: "/waypoint_files/map_waypoints.txt"
  gps_coordinates_file: "/waypoint_files/test_gps_waypoints.txt"